In [159]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [160]:
df=pd.read_csv('loan_dataset_new')

In [161]:
df.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers  ...  m4  m5 m6  m7  m8  m9  m10  m11  \
0             95                  1.0  ...   0   0  0   1   0   0    0    0   
1             72                  1.0  ...   0   0  0   0   0   0    0    1   
2             49                  1.0  ...   0   0  0   0   0   0    0    0   
3             46                  2.0  ...   0   0  0   0   0   1    1    1   
4             80                  1.0  ...   3   4  5   6   7   8    9   10   

   m12  m13  
0    0    1  
1    0    1  
2    0    1  
3    1    1  
4   11    1  

[5 rows x 29 columns]

In [162]:
df.shape

(116058, 29)

In [163]:
df.isnull().sum()

loan_id                     0
source                      0
financial_institution       0
interest_rate               0
unpaid_principal_bal        0
loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
m1                          0
m2                          0
m3                          0
m4                          0
m5                          0
m6                          0
m7                          0
m8                          0
m9                          0
m10                         0
m11                         0
m12                         0
m13                         0
dtype: int64

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   loan_id                   116058 non-null  int64  
 1   source                    116058 non-null  object 
 2   financial_institution     116058 non-null  object 
 3   interest_rate             116058 non-null  float64
 4   unpaid_principal_bal      116058 non-null  int64  
 5   loan_term                 116058 non-null  int64  
 6   origination_date          116058 non-null  object 
 7   first_payment_date        116058 non-null  object 
 8   loan_to_value             116058 non-null  int64  
 9   number_of_borrowers       116058 non-null  float64
 10  debt_to_income_ratio      116058 non-null  float64
 11  borrower_credit_score     116058 non-null  float64
 12  loan_purpose              116058 non-null  object 
 13  insurance_percent         116058 non-null  f

In [165]:
df.columns

Index(['loan_id', 'source', 'financial_institution', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'm1',
       'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12',
       'm13'],
      dtype='object')

In [166]:
df1=df.drop('loan_id',axis=1)

In [167]:
cat_columns=df1[['source', 'financial_institution','origination_date','first_payment_date','loan_purpose']]

In [168]:
df1_enc=pd.get_dummies(cat_columns)

In [169]:
df1_enc

source_X  source_Y  source_Z  financial_institution_Anderson-Taylor  \
0              0         0         1                                      0   
1              0         1         0                                      0   
2              0         0         1                                      0   
3              1         0         0                                      0   
4              1         0         0                                      0   
...          ...       ...       ...                                    ...   
116053         0         1         0                                      0   
116054         0         0         1                                      0   
116055         1         0         0                                      0   
116056         1         0         0                                      0   
116057         0         0         1                                      0   

        financial_institution_Browning-Hart  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   
...                                     ...   
116053                                    1   
116054                                    0   
116055                                    0   
116056                                    0   
116057                                    0   

        financial_institution_Chapman-Mcmahon  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   
...                                       ...   
116053                                      0   
116054                                      0   
116055                                      0   
116056                                      0   
116057                                      0   

        financial_institution_Cole, Brooks and Vincent  \
0                                                    0   
1                                                    0   
2                                                    0   
3                                                    0   
4                                                    0   
...                                                ...   
116053                                               0   
116054                                               0   
116055                                               0   
116056                                               0   
116057                                               0   

        financial_institution_Edwards-Hoffman  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   
...                                       ...   
116053                                      0   
116054                                      0   
116055                                      0   
116056                                      0   
116057                                      0   

        financial_institution_Martinez, Duffy and Bird  \
0                                                    0   
1                                                    0   
2                                                    0   
3                                                    0   
4                                                    0   
...                                                ...   
116053                                               0   
116054                                               0   
116055                                               0   
116056                                 

In [170]:
df1_enc.dtypes

source_X                                             uint8
source_Y                                             uint8
source_Z                                             uint8
financial_institution_Anderson-Taylor                uint8
financial_institution_Browning-Hart                  uint8
financial_institution_Chapman-Mcmahon                uint8
financial_institution_Cole, Brooks and Vincent       uint8
financial_institution_Edwards-Hoffman                uint8
financial_institution_Martinez, Duffy and Bird       uint8
financial_institution_Miller, Mcclure and Allen      uint8
financial_institution_Nicholson Group                uint8
financial_institution_OTHER                          uint8
financial_institution_Richards-Walters               uint8
financial_institution_Richardson Ltd                 uint8
financial_institution_Romero, Woods and Johnson      uint8
financial_institution_Sanchez, Hays and Wilkerson    uint8
financial_institution_Sanchez-Robinson               uin

In [171]:
from sklearn.preprocessing import MinMaxScaler

In [172]:
minmax= MinMaxScaler()

In [173]:
x=df1.drop(['source', 'financial_institution','origination_date','first_payment_date','loan_purpose','m13'],axis=1)

In [174]:
z=df1['m13']

In [175]:
x1=minmax.fit_transform(x)

In [176]:
#converting back to dataframe
x1=pd.DataFrame(x1,columns=x.columns)

In [177]:
x1.describe()

interest_rate  unpaid_principal_bal      loan_term  loan_to_value  \
count  116058.000000         116058.000000  116058.000000  116058.000000   
mean        0.359769              0.165876       0.774270       0.675076   
std         0.102449              0.096455       0.299208       0.190019   
min         0.000000              0.000000       0.000000       0.000000   
25%         0.277778              0.091674       0.400000       0.560440   
50%         0.361111              0.144659       1.000000       0.725275   
75%         0.416667              0.224558       1.000000       0.813187   
max         1.000000              1.000000       1.000000       1.000000   

       number_of_borrowers  debt_to_income_ratio  borrower_credit_score  \
count        116058.000000         116058.000000          116058.000000   
mean              0.593186              0.472100               0.916579   
std               0.491242              0.154457               0.050251   
min               0.000000              0.000000               0.000000   
25%               0.000000              0.349206               0.894048   
50%               1.000000              0.476190               0.930952   
75%               1.000000              0.603175               0.952381   
max               1.000000              1.000000               1.000000   

       insurance_percent  co-borrower_credit_score  insurance_type  ...  \
count      116058.000000             116058.000000   116058.000000  ...   
mean            0.069657                  0.549775        0.003257  ...   
std             0.202412                  0.456874        0.056977  ...   
min             0.000000                  0.000000        0.000000  ...   
25%             0.000000                  0.000000        0.000000  ...   
50%             0.000000                  0.885167        0.000000  ...   
75%             0.000000                  0.946172        0.000000  ...   
max             1.000000                  1.000000        1.000000  ...   

                  m3             m4             m5             m6  \
count  116058.000000  116058.000000  116058.000000  116058.000000   
mean        0.000395       0.000363       0.000505       0.000428   
std         0.011085       0.010360       0.011805       0.010944   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                  m7             m8             m9            m10  \
count  116058.000000  116058.000000  116058.000000  116058.000000   
mean        0.000462       0.000483       0.000487       0.000551   
std         0.011218       0.011313       0.011658       0.012369   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

                 m11            m12  
count  116058.000000  116058.000000  
mean        0.000547       0.000576  
std         0.012530       0.012723  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.000000       0.000000  
75%         0.000000       0.000000  
max         1.000000       1.000000  

[8 rows x 22 columns]

In [178]:
x1.columns

Index(['interest_rate', 'unpaid_principal_bal', 'loan_term', 'loan_to_value',
       'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'm1',
       'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12'],
      dtype='object')

In [179]:
x2=pd.concat([df1_enc,x1,z],axis=1)

In [ ]:
x2.columns

In [183]:
X=x2.drop('m13',axis=1)
y=x2['m13']

#Hold Out technique 

In [184]:
from sklearn.model_selection import train_test_split

In [185]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#1.Logistic Regression Model

In [186]:
from sklearn.linear_model import LogisticRegression

In [187]:
lr=LogisticRegression(max_iter=1000)
lr_model=lr.fit(x_train,y_train)

In [188]:
score_lr=lr_model.score(x_test,y_test)

In [189]:
score_lr

0.9953903153541271

#a) K fold Cross Validation of Logistic Regression Model

In [190]:
from sklearn.model_selection import KFold

In [191]:
kfold_validator=KFold(10)#no of folds=

In [192]:
from sklearn.utils import shuffle#Using shuffle() method of scikit-learn, in order to shuffle a DataFrame

In [193]:
X, y = shuffle(X, y, random_state=42)#shuffling the X and y to avoid the fit failed warning error generated as valueerror: this solver needs samples of at least 2 classes in the data, but the data contains only one class: 0.0

In [ ]:
for train_index,test_index in kfold_validator.split(X,y):
  print('Training Index',train_index)
  print('Testing Index',test_index)

In [195]:
from sklearn.model_selection import cross_val_score

In [196]:
cv_result=cross_val_score(lr_model,X,y,cv=kfold_validator)

In [197]:
cv_result

array([0.99534723, 0.99569188, 0.99500258, 0.99517491, 0.99586421,
       0.99508875, 0.99586421, 0.99603653, 0.99474364, 0.99551917])

In [198]:
np.mean(cv_result)

0.9954333126212112

#b) Stratified Cross Validation of Logistic Regression Model

In [199]:
from sklearn.model_selection import StratifiedKFold

In [200]:
skfold_validator=StratifiedKFold(n_splits=6)#no of folds=6

In [ ]:
for train_index,test_index in skfold_validator.split(X,y):
  print('Training Index',train_index)
  print('Testing Index',test_index)

In [202]:
skcv_result=cross_val_score(lr_model,X,y,cv=skfold_validator)

In [203]:
skcv_result

array([0.99550225, 0.99529546, 0.99524376, 0.99519206, 0.99560565,
       0.99524376])

In [204]:
np.mean(skcv_result)

0.9953471540092024

#2.SVM Model

In [205]:
from sklearn.svm import SVC#support vector classifier

In [206]:
svm_clf=SVC(kernel='rbf')#kernel choosen is rbf(default)

In [207]:
svm_model=svm_clf.fit(x_train,y_train)#Hold Out method

In [208]:
y_pred_svm=svm_model.predict(x_test)

In [209]:
#for classification algorithm models validation checking confusion matrix,accuracy score,precision score and recall score can be used
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,accuracy_score

In [210]:
confusion_matrix(y_test,y_pred_svm)#confusion matrix of svm model

array([[23084,     0],
       [  113,    15]])

In [211]:
accuracy_score(y_test,y_pred_svm)#accuracy score 

0.995131828364639

#a) K FOLD Cross Validation of SVM Model

In [212]:
kfold_validator_svm=KFold(6)#no of folds=10

In [ ]:
for train_index,test_index in kfold_validator_svm.split(X,y):
  print('Training Index',train_index)
  print('Testing Index',test_index)

In [214]:
cv_result_svm=cross_val_score(svm_model,X,y,cv=kfold_validator_svm)

In [215]:
cv_result_svm

array([0.99503696, 0.99514036, 0.99508866, 0.99498527, 0.99560565,
       0.99426149])

In [216]:
np.mean(cv_result_svm)

0.9950197315135535

#b) Stratified Cross Validation of SVM Model

In [217]:
skfold_validator_svm=StratifiedKFold(n_splits=10)#no of folds=10

In [ ]:
for train_index,test_index in skfold_validator_svm.split(X,y):
  print('Training Index',train_index)
  print('Testing Index',test_index)

In [219]:
skcv_result_svm=cross_val_score(svm_model,X,y,cv=skfold_validator_svm)

In [220]:
skcv_result_svm

array([0.99526107, 0.99517491, 0.99517491, 0.99491642, 0.99491642,
       0.99500258, 0.99483026, 0.99534723, 0.99474364, 0.99491598])

In [221]:
np.mean(skcv_result_svm)

0.9950283444738022

#Conclusion:-

In [225]:
print('THE AVERAGE K FOLD CROSS VALIDATION SCORE OF LOGISTIC REGRESSION MODEL IS:',np.mean(cv_result))
print('\n')
print('THE AVERAGE K FOLD CROSS VALIDATION SCORE OF SVM MODEL IS:',np.mean(cv_result_svm))
print('\n')
print('THE AVERAGE STRATIFIED CROSS VALIDATION SCORE OF LOGISTIC REGRESSION :',np.mean(skcv_result))
print('\n')
print('THE AVERAGE STRATIFIED CROSS VALIDATION SCORE OF SVM MODEL IS:',np.mean(skcv_result_svm))


THE AVERAGE K FOLD CROSS VALIDATION SCORE OF LOGISTIC REGRESSION MODEL IS: 0.9954333126212112


THE AVERAGE K FOLD CROSS VALIDATION SCORE OF SVM MODEL IS: 0.9950197315135535


THE AVERAGE STRATIFIED CROSS VALIDATION SCORE OF LOGISTIC REGRESSION : 0.9953471540092024


THE AVERAGE STRATIFIED CROSS VALIDATION SCORE OF SVM MODEL IS: 0.9950283444738022


#a) The Averages of both K Fold Cross Validation scores and Stratified Cross Validation scores are seems to be same for both Logistic Regression Model and SVM Model.

#b) So the performance of both Logistic Regression Model and SVM Model are same on Loan dataset.